"""The whole sub-app roster this library ships, built over one declaration.

A project naming its inherited sub-apps one by one puts the roster on the
wrong side of the boundary between the two halves of lup. The library
arrives through a lock refresh and the template through a hand-replayed commit,
so a sub-app added here reaches a project's dependencies immediately and its
``--help`` never: the name sits in a copied file nobody has reason to
revisit, and an absent sub-app reads exactly like a declined one.

So the default is everything, and a project states its delta. What makes that
possible is that the factories need only the handful of facts
:class:`DevtoolsDeclarations` carries, every one of which a project already
declares once for something else — which also retires the other half of the
drift, because a factory that grows an argument grows a field there with a
default rather than breaking a call site in every downstream at once.

One table, two renderings. Prose about the CLI is generated into the harness
and the harness is generated by the CLI, so a document naming the roster must
reach it without constructing a Typer app; :data:`LIBRARY_SPECS` is that
reading and :meth:`DevtoolsDeclarations.roster` the other. Both project the
same entries, so a roster the documents describe and a roster the CLI serves
cannot disagree.
"""

from collections.abc import Callable
from functools import partial
from pathlib import Path

import typer
from pydantic import BaseModel

from lup.devtools.coordination.app import create_coordination_app
from lup.devtools.dashboard.reviews import create_operator_dashboard_app
from lup.devtools.ledger.app import create_ledger_app
from lup.ledger.models import LedgerEdge, LedgerNode
from lup.ledger.store import LedgerLayout
from lup.ledger.writeup import Writeup, write_writeup
from lup.devtools.dev.app import create_dev_app
from lup.devtools.dev.commands import CommandSurface
from lup.devtools.dev.declarations import DevDeclarations
from lup.devtools.feedback.app import create_feedback_app
from lup.devtools.feedback.models import AgentPrompt
from lup.devtools.git.app import create_git_app
from lup.devtools.harness.app import create_harness_app
from lup.devtools.harness.composition import NativeTargets
from lup.devtools.harness.drift import RepositoryWriter
from lup.devtools.harness.launch import LaunchCheckpoint, LaunchMode
from lup.devtools.harness.resolve import ConfiguredModel
from lup.launch.declaration import OuterContainer
from lup.devtools.resolve.app import create_resolve_app
from lup.devtools.review.app import create_review_app
from lup.devtools.run.app import create_run_app
from lup.devtools.setup import Integration, create_setup_app
from lup.devtools.subapps import SubApp, SubAppSpec
from lup.devtools.trace.app import create_trace_app
from lup.providers.profiles import ProfileDirectory
from lup.observability.usage.app import UsageEntry

import lup.devtools.sync as sync
import lup.devtools.tools as tools
import lup.devtools.trace.app as trace
import lup.devtools.version as version


class DevtoolsDeclarations(BaseModel, frozen=True, arbitrary_types_allowed=True):
    """Everything the sub-apps this library ships need from one repository.

    Each field is a fact only the project has, and every one of them it already
    holds for another reason — so composing the roster asks for nothing new,
    which is what lets the roster itself stop being the project's to write.
    """

    dev: Callable[[], DevDeclarations]
    """What the dev tree reads about this repository, when a command runs."""

    targets: NativeTargets
    """Every native runtime this project generates a tree for."""

    repository_writers: list[RepositoryWriter]
    """Generated files that belong to no single native tree."""

    command_surface: Callable[[], CommandSurface] | None = None
    """Every command this project's composed CLI serves, when it can say.

    Deferred rather than taken as a value, for the reason the command
    reference is written by a closure: these declarations are built before the
    sub-apps are mounted onto the root, so a surface read here would be read
    off half a CLI. A project declaring none keeps every check but the one
    that reads it, which is the honest answer for a roster composed without a
    root to walk."""

    prompt: Callable[[], AgentPrompt] | None = None
    """This project's system prompt, as the health report weighs it.

    Read by the ``feedback`` sub-app alone, so a project that does not serve
    it — one with no agent of its own to prompt, having declined the feedback
    loop — declares none rather than inventing one. Serving the sub-app
    without it is refused where the roster is built.
    """

    relocate_roots: list[Path] = [Path("src"), Path("tests")]
    """Where `dev relocate` may move a module, for a project laid out that way."""

    integrations: list[Integration] = []
    """External services the setup wizard and dashboard walk an operator through."""

    usage_entries: list[UsageEntry] = []
    """One entry per backend whose account this project reads usage from.

    A project naming none retires ``usage`` rather than declaring an empty
    list into a served command tree, so a display over zero accounts is a
    decision `dev check` can name instead of an emptiness a reader discovers."""

    model: ConfiguredModel | None = None
    """The model a launch selects when the caller names none."""

    profiles: ProfileDirectory | None = None
    """The accounts this project keeps, where it keeps its own."""

    launch_modes: list[LaunchMode] = []
    """Named ways of opening a session that this project's default is not.

    Empty for a project whose sessions are all the same kind. One entry adds
    a flag to every launcher, compiles the tree that mode declares while it is
    in force, and opens whatever that kind of session needs around the run."""

    launch_checkpoint: LaunchCheckpoint | None = None
    """Application data saved before generation and after the native CLI closes."""

    launch_container: OuterContainer = OuterContainer()
    """What this project's contained sessions are granted — network, memory,
    sudo, devices, folders, held trees — under a person's ``[container]``
    config, a mode and the command line, each of which may overrule it."""

    node_classes: list[type[LedgerNode]] = []
    """The node types this project records, for the reader that shows all.

    Needed only by the console, which turns a stored record into some
    class to ask its standing; everything else asks the store for the
    type it wants and never sees a list. Empty for a project that
    records nothing, which still reads the DAG as the base class. The
    library declares none of these, because what a node type is for is a
    project's question."""

    edge_classes: list[type[LedgerEdge]] = []
    """The relations this project draws, for the command that relates two nodes.

    Declared beside the node types and for the same reason: an edge kind is
    the project's vocabulary, and a generic `relate` has to know which class
    to validate a spelled kind against."""

    writeups: list[Writeup] = []
    """The documents this project generates from its ledger.

    Declared in Python the way guidance is, and written by `ledger writeup`.
    One whose every rendered kind is committed joins the drift-checked
    generation as well, since every machine then renders the same document;
    one rendering a local kind is `ledger writeup`'s alone, because the
    local half is live state each machine holds its own copy of."""

    ledger: LedgerLayout = LedgerLayout()
    """Where this project keeps its log: one log in two journals, placed per kind.

    Every kind is local by default — under the git directory every worktree
    resolves to, which is the answer to a ledger that forks — and a project
    declares which kinds are committed instead, in a journal in the tree,
    merged by union, reviewed in a diff and identical on every machine. The
    store, the console, the tool group, the explorer and the gate all read
    this one declaration."""

    def writers(self) -> list[RepositoryWriter]:
        """Every generated file outside a native tree, the writeups among them
        whose every rendered kind is committed."""
        return [
            *self.repository_writers,
            *writeup_writers(self.ledger, self.writeups, self.node_classes),
        ]

    def roster(self, retired: list[str] | None = None) -> list[SubApp]:
        """Every sub-app the library ships, wired over these declarations.

        ``retired`` is what a project has declined, and an entry named there is
        *not built* rather than built and dropped afterwards. That distinction
        is the whole reason this takes an argument: a builder may import an
        optional extra, so constructing an app a project declined makes that
        project carry a dependency for a command it does not serve. Measured —
        a project retiring ``dashboard`` still could not start its CLI without
        ``lup-agents[web]``, because the roster built the dashboard before the
        selection ever saw it.

        Defaulting to none keeps every existing caller correct: a project that
        declines nothing gets exactly what it got before.
        """
        declined = retired or []
        return [
            entry.wired(self)
            for entry in LIBRARY_ROSTER
            if entry.spec.name not in declined
        ]


def writeup_writers(
    layout: LedgerLayout,
    writeups: list[Writeup],
    classes: list[type[LedgerNode]],
) -> list[RepositoryWriter]:
    """The writeups as generated files, where every kind each renders is committed.

    A writeup rendered from kinds every machine holds identically is a
    generated file like any other, so it joins the drift-checked generation:
    `harness generate all` writes it and `dev check` refuses one that is
    behind. One rendering a local kind — or one whose parts name nodes
    rather than kinds, and so cannot say — stays `ledger writeup`'s alone,
    since the same declaration renders differently where nothing was
    recorded.
    """
    return [
        partial(write_writeup, writeup, classes, layout=layout)
        for writeup in writeups
        if (kinds := writeup.kinds()) is not None and layout.tracked(kinds)
    ]


class RosterEntry(BaseModel, frozen=True, arbitrary_types_allowed=True):
    """One sub-app the library ships: what it is called, and how it is built.

    The pair is what makes the two readings one table. A roster listed for a
    document and a roster wired into a CLI are the same entries seen through
    different halves of this model, so neither can name a sub-app the other
    does not.
    """

    spec: SubAppSpec
    build: Callable[[DevtoolsDeclarations], typer.Typer]

    def wired(self, declared: DevtoolsDeclarations) -> SubApp:
        """This entry as a composable sub-app, over one project's declaration."""
        return SubApp(spec=self.spec, app=self.build(declared))


def conversation_app(declared: "DevtoolsDeclarations") -> typer.Typer:
    """The conversation sub-app, imported where it is built.

    Deferred because retaining a hosted transcript drives a real browser,
    which is the ``conversation`` extra. A module-level import makes that extra
    a requirement of importing this file at all — so a project that declines
    the sub-app still could not start its CLI without it.
    """
    from lup.devtools.conversation.app import create_conversation_app

    return create_conversation_app(declared.profiles)


def feedback_app(declared: "DevtoolsDeclarations") -> typer.Typer:
    """The feedback sub-app, over the prompt its health report weighs.

    Refused rather than built without one. Every other feedback command reads
    records any project's loop writes the same way, but ``prompt-health``
    weighs the one thing only the application assembles, so a sub-app served
    without it carries a command that can do nothing but fail — and fail long
    after the composition that could have said why. Both ways out are named,
    because which is right depends on whether the project has an agent at all.
    """
    if declared.prompt is None:
        raise ValueError(
            "the `feedback` sub-app weighs this project's agent prompt, and "
            "DevtoolsDeclarations declares none: pass `prompt=` a callable "
            "returning its AgentPrompt, or stop serving `feedback` — declining "
            "the feedback-loop module retires it"
        )
    return create_feedback_app(declared.prompt)


# lup: ignore[library-default] — the sub-apps this library authors, so the table
# is what it ships rather than a choice made for an adopter
LIBRARY_ROSTER = [
    RosterEntry(
        spec=SubAppSpec(
            name="conversation", help="Retain authenticated AI conversations"
        ),
        build=lambda declared: conversation_app(declared),
    ),
    RosterEntry(
        spec=SubAppSpec(
            name="coordination",
            help="Reach the other sessions working in this repository",
        ),
        build=lambda _: create_coordination_app(),
    ),
    RosterEntry(
        spec=SubAppSpec(
            name="dashboard",
            help="Serve the operator's page over the parked reviews",
        ),
        build=lambda _: create_operator_dashboard_app(Path.cwd()),
    ),
    RosterEntry(
        spec=SubAppSpec(
            name="ledger",
            help="Read and preserve the notes this repository has recorded",
        ),
        build=lambda declared: create_ledger_app(
            declared.node_classes,
            declared.edge_classes,
            declared.writeups,
            declared.ledger,
        ),
    ),
    RosterEntry(
        spec=SubAppSpec(
            name="dev", help="Read this repository, and hold it to what it settled"
        ),
        build=lambda declared: create_dev_app(
            declared=declared.dev,
            native_targets=declared.targets,
            repository_writers=declared.writers(),
            relocate_roots=declared.relocate_roots,
            usage_entries=declared.usage_entries,
            node_classes=declared.node_classes,
            ledger=declared.ledger,
            command_surface=declared.command_surface,
        ),
    ),
    RosterEntry(
        spec=SubAppSpec(name="feedback", help="Feedback state, metrics, and commits"),
        build=lambda declared: feedback_app(declared),
    ),
    RosterEntry(
        spec=SubAppSpec(
            name="git", help="Branches, worktrees, pull requests, and conflicts"
        ),
        build=lambda declared: create_git_app(declared.dev),
    ),
    RosterEntry(
        spec=SubAppSpec(
            name="harness", help="Generate and launch the native harnesses"
        ),
        build=lambda declared: create_harness_app(
            declared.targets,
            declared.writers(),
            declared.model,
            declared.profiles,
            declared.launch_modes,
            declared.launch_checkpoint,
            node_classes=declared.node_classes,
            ledger=declared.ledger,
            container=declared.launch_container,
        ),
    ),
    RosterEntry(
        spec=SubAppSpec(
            name="resolve", help="Drive a resolver run, and watch or answer it"
        ),
        build=lambda declared: create_resolve_app(
            declared.dev, declared.targets, declared.model, declared.profiles
        ),
    ),
    RosterEntry(
        spec=SubAppSpec(
            name="review",
            help="The parked reviews an operator answers, and what each waits on",
        ),
        build=lambda declared: create_review_app(
            Path.cwd(), lambda: declared.dev().hooks
        ),
    ),
    RosterEntry(
        spec=SubAppSpec(name="run", help="Follow work that outlives its tool call"),
        build=lambda _: create_run_app(),
    ),
    RosterEntry(
        spec=SubAppSpec(name="setup", help="Interactive setup wizard, and its page"),
        build=lambda declared: create_setup_app(
            declared.integrations, declared.profiles
        ),
    ),
    RosterEntry(spec=sync.SUBAPP.spec, build=lambda _: sync.SUBAPP.app),
    RosterEntry(spec=tools.SUBAPP.spec, build=lambda _: tools.SUBAPP.app),
    RosterEntry(spec=trace.SUBAPP_SPEC, build=lambda _: create_trace_app()),
    RosterEntry(spec=version.SUBAPP.spec, build=lambda _: version.SUBAPP.app),
]
"""Every sub-app lup ships, in the order `--help` lists them.

Each name is owned by exactly one module, which is the property this list
is arranged for rather than a count it happened to reach. A module claims a
top-level name and a project declining the module stops being served everything
beneath it — so a command sitting under a name some other module owns is a
command no project can decline, and there were about forty of them. `dev` is
the core module's rather than a place for whatever had nowhere to go; the git
loop, the resolver, a background run and a session's records each have their
own, and the three trees that were top-level and core's anyway sit inside it.
"""

LIBRARY_SPECS = [entry.spec for entry in LIBRARY_ROSTER]
"""The roster as a document names it, reachable without constructing an app.

The other reading is :meth:`DevtoolsDeclarations.roster`, which projects the
same table into wired sub-apps. Both are this list of entries seen through one
half of :class:`RosterEntry`, so neither can name a sub-app the other does not.
"""
