"""The command tree for what a session left behind: its trace and its records.

Two readings of one subject, so one sub-app rather than two. What a session did
is its trace; where its records go once its worktree is gone is the archive. A
project with no use for either declines the observability module and loses
both, which is what putting them under one owner is for.

What a session *spent* is deliberately not here, though it reads like the third
of a set. Everything here reads what a session wrote into this repository, and
the usage display reads the backend's own metered account — a different source,
answering whether or not a session ever ran here. It sits under ``dev``.
"""

from typing import Annotated

import typer

import lup.devtools.dev.traces as records
import lup.devtools.trace.traces as traces
from lup.workspace.history import resolve_version
from lup.devtools.subapps import SubAppSpec
from lup.devtools.utils import VERSION_OPT, ALL_VERSIONS_OPT, JSON_OPT

SUBAPP_SPEC = SubAppSpec(
    name="trace", help="What a session left behind: its trace and its records"
)
"""What this tree is called, reachable without building it.

A spec rather than a wired :class:`~lup.devtools.subapps.SubApp`, so that prose
about the CLI can name it without constructing it — the harness is generated by
the CLI, and a document that built the app to learn its name would close that
loop.
"""


def create_trace_app() -> typer.Typer:
    """Wire the tree over what a session left in this repository."""
    app = typer.Typer(no_args_is_help=True)

    @app.command("show")
    def show_cmd(
        session_id: Annotated[str, typer.Argument(help="Session ID to show trace for")],
        full: Annotated[
            bool,
            typer.Option("-f", "--full", help="Show full trace"),
        ] = False,
        tool_calls: Annotated[
            bool,
            typer.Option(
                "--tool-calls", "-t", help="Tool-call timeline from the trace's events"
            ),
        ] = False,
        as_json: JSON_OPT = False,
    ) -> None:
        """Show trace for a session."""
        traces.show(session_id, full, tool_calls, as_json)

    @app.command("search")
    def search_cmd(
        pattern: Annotated[str, typer.Argument(help="Pattern to search for (regex)")],
        context: Annotated[
            int,
            typer.Option("-C", help="Lines of context around match"),
        ] = 2,
        as_json: JSON_OPT = False,
    ) -> None:
        """Search traces for a pattern."""
        traces.search(pattern, context, as_json)

    @app.command("list")
    def list_cmd(
        limit: Annotated[
            int,
            typer.Option("-n", "--limit", help="Max to show"),
        ] = 20,
        version: VERSION_OPT = None,
        all_versions: ALL_VERSIONS_OPT = False,
        as_json: JSON_OPT = False,
    ) -> None:
        """List available traces."""
        scope = resolve_version(version, all_versions)
        effective, warning = scope.versions, scope.warning
        if warning:
            typer.echo(warning)
        traces.list_traces(limit, effective, as_json)

    @app.command("errors")
    def errors_cmd(
        limit: Annotated[
            int,
            typer.Option("-n", "--limit", help="Max errors to show"),
        ] = 20,
        version: VERSION_OPT = None,
        all_versions: ALL_VERSIONS_OPT = False,
        as_json: JSON_OPT = False,
    ) -> None:
        """Show sessions with errors found in trace files."""
        scope = resolve_version(version, all_versions)
        effective, warning = scope.versions, scope.warning
        if warning:
            typer.echo(warning)
        traces.errors_in_traces(limit, effective, as_json)

    @app.command("capabilities")
    def capabilities_cmd(
        as_json: JSON_OPT = False,
    ) -> None:
        """Extract capability requests from traces."""
        traces.capabilities(as_json)

    @app.command("verify")
    def verify_cmd(
        runs: Annotated[
            list[str] | None,
            typer.Argument(
                help="Run ids, run directories or transcripts; none checks every launch"
            ),
        ] = None,
        as_json: JSON_OPT = False,
    ) -> None:
        """Check that each launch transcript's hash chain holds, and say where it breaks.

        Every launched session writes a hash-chained journal of what its runtime
        exposed. Each record carries its place and the digest of the one before
        it, so an edit, a removal, an insertion or a reordering anywhere but the
        very end breaks the chain at that record. Exits 1 when any breaks, so a
        script can stop on it; a tail cut off cleanly is the ledger's pinned
        digest to answer for, not the chain's.
        """
        traces.verify_transcripts(runs or [], as_json)

    @app.command("events")
    def events_cmd(
        run: Annotated[
            str, typer.Argument(help="A run id, run directory, or transcript")
        ],
        kinds: Annotated[
            list[str] | None,
            typer.Option("--kind", help="Only records of this kind; repeatable"),
        ] = None,
        as_json: JSON_OPT = False,
    ) -> None:
        """Read a launched session's transcript, record by record, its chain checked first.

        The chain's standing comes before any record, and where it breaks a line
        marks the record it breaks on: what precedes it is vouched for by the
        chain, and what follows is not.
        """
        traces.transcript_events(run, kinds or [], as_json)

    @app.command("archive")
    def archive_cmd(
        name: Annotated[
            str,
            typer.Argument(help="Branch whose worktree records should be kept"),
        ],
        dry_run: Annotated[
            bool,
            typer.Option("--dry-run", "-n", help="Report what would be copied"),
        ] = False,
        as_json: Annotated[
            bool,
            typer.Option("--json", help="Output as JSON"),
        ] = False,
    ) -> None:
        """Copy a worktree's session records into the archive beside the repository.

        `git delete` already does this, so reach for it to read what a deletion
        would keep before deciding one, or to archive a worktree that is staying.
        """
        records.report(name, dry_run, as_json)

    return app
